theme = "bento"
languageCode = "en-us"
baseurl = "https://main.d2mtzr255y9kly.amplifyapp.com"
title = "Mach50"

author = "Rock Whitney"
copyright = "MIT"

[taxonomies]
category = "categories"
tag = "tags"

# Better code higlighting
# via https://discourse.gohugo.io/t/pygmentscodefences-how-to-choose-themes/3842/3
pygmentsCodefences = true
pygmentsStyle = "vs"

# Integrations
googleAnalytics = "UA-XXXXXX-YY"
disqusShortname = "bento-hugo-theme"

# Hightlight theme
[markup.highlight]
  style = "github"

# Allow HTML rendering inside markdown
[markup.goldmark.renderer]
  unsafe = true

[params]
  # Show intro in the home page (with headline and description)
  intro = true
  headline = "This is a Mach50"
  description = "A minimalist theme"

  # Copyright note in the footer
  copyright = "Copyright © 2020 Someone"

  # Image in the homepage. You can setup a different image for social media
  cover = "images/vancouver.jpg"
  ogImage = "images/og_image.jpg"

  # Social media usernames
  github = "leonardofaria/bento"
  twitter = "rock2crush"
  linkedin = "https://www.linkedin.com/in/rockwhitney/"
  email = "rock@mach50.com"

  # Learn more about webmention 
  # https://sebastiandedeyne.com/adding-webmentions-to-my-blog/
  # webmention = ""
  # productionBaseUrl is need if you want to receive webmentions in local environment
  # productionBaseUrl = "https://mach50.com"

  # Avatar (shown in the homepage)
  #avatar = "images/avatar.jpg"
  #avatar = "images/rockaws.jpeg"
  # Bio is shown in the end of posts
  authorBio = "Bento is a doggo who likes to code. Follow him on <a href='#'>Twitter</a>"

# If you want to use fathom (https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
  siteID = "XXXXX"
  # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
  serverURL = "analytics.example.com"

# If you want to use umami (https://umami.is/) for analytics, add this section
[params.umami]
  siteID = "XXXXX"
  trackerScript = "//umami.example.com/umami.js"

# Items in the top menu
[menu]
  [[menu.main]]
      name = "About"
      url = "/about"
      weight = 1

  [[menu.main]]
      name = "Archives"
      url = "/archives"
      weight = 1

  [[menu.main]]
      name = "Source code"
      url = "https://github.com/rockkw/machbento"
      weight = 1


[deployment]

[[deployment.targets]]
name = "mach50.com"
URL = "s3://mach50.com?region=us-west-2"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
# cloudFrontDistributionID =	"[CLOUDFRONT_DIST_ID]"

[[deployment.matchers]]
# Cache static assets for 20 years.
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true